baseURL = "https://dengyuncheng27.github.io/site-nav"
languageCode = "zh-CN"
title = "小站导航"
theme = "nav"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
homepage = "https://github.com/DengYuncheng27"
[params]
  author = "BUBBLE"
  description = "个人导航网"
[params.search]
  enable = true
[params.darkmode]
  enable = false
[author]
  name = "Bubble"
  homepage = "https://github.com/DengYuncheng27"