baseURL = "https://dengyuncheng27.github.io/site-nav"
languageCode = "zh-CN"
title = "小站导航"
theme = "nav"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "iplaycode"
  description = "Webstack Hugo"
[params.search]
  enable = true
[params.darkmode]
  enable = false